#!/usr/bin/env bash
# lib/task.sh — task directory CRUD
#
# Tasks live under "$SCHEDULER_ROOT/tasks/<name>/" and contain:
#   task.yaml   flat key: value config
#   prompt.md   the prompt fed to `claude -p`
#
# Exposes:
#   task_dir <name>              → absolute path of the task directory
#   task_list                    → newline-separated task names (sorted)
#   task_exists <name>           → return 0/1
#   task_scaffold <name> <opts>  → create dir + files (see below)
#   task_remove <name>           → rm -rf the dir; idempotent
#   task_field <name> <key>      → shorthand: yaml_get on task.yaml

set -euo pipefail

# Resolve the scheduler root if the caller has not set it.
: "${SCHEDULER_ROOT:?SCHEDULER_ROOT must be set by caller}"

# shellcheck source=common.sh
source "$SCHEDULER_ROOT/lib/common.sh"

task_dir() {
    local name="$1"
    echo "$SCHEDULER_ROOT/tasks/$name"
}

task_exists() {
    local name="$1"
    [[ -d "$(task_dir "$name")" ]]
}

task_list() {
    local root="$SCHEDULER_ROOT/tasks"
    if [[ ! -d "$root" ]]; then
        return 0
    fi
    # List immediate subdirs only
    (
        cd "$root"
        for d in */; do
            [[ -d "$d" ]] || continue
            echo "${d%/}"
        done
    ) | sort
}

task_field() {
    local name="$1"
    local key="$2"
    local f
    f="$(task_dir "$name")/task.yaml"
    yaml_get "$key" "$f"
}

# task_scaffold <name>
# Inputs via environment (set by caller):
#   TASK_PROMPT_FILE        required — source prompt to copy into prompt.md
#   TASK_OUTPUT_FILE        optional
#   TASK_OUTPUT_DIR         optional
#   TASK_ALLOWED_TOOLS      optional
#   TASK_ADD_DIRS           optional
#   TASK_SKIP_IF_EXISTS     optional (default: true)
#   TASK_SCHEDULE           required — stored in task.yaml for reference/reconstruction
#   TASK_CLAUDE_BIN         optional
task_scaffold() {
    local name="$1"
    local dir
    dir="$(task_dir "$name")"

    if [[ -z "${TASK_PROMPT_FILE:-}" ]]; then
        log_error "TASK_PROMPT_FILE is required"
        return 1
    fi
    if [[ ! -f "$TASK_PROMPT_FILE" ]]; then
        log_error "prompt file does not exist: $TASK_PROMPT_FILE"
        return 1
    fi
    if [[ -z "${TASK_SCHEDULE:-}" ]]; then
        log_error "TASK_SCHEDULE is required"
        return 1
    fi

    mkdir -p "$dir"
    cp "$TASK_PROMPT_FILE" "$dir/prompt.md"

    local yaml="$dir/task.yaml"
    {
        echo "# Task definition for $name (generated by scheduler add)"
        echo "schedule: \"${TASK_SCHEDULE}\""
        if [[ -n "${TASK_OUTPUT_DIR:-}" ]]; then
            echo "output_dir: \"${TASK_OUTPUT_DIR}\""
        fi
        if [[ -n "${TASK_OUTPUT_FILE:-}" ]]; then
            echo "output_file: \"${TASK_OUTPUT_FILE}\""
        fi
        if [[ -n "${TASK_ALLOWED_TOOLS:-}" ]]; then
            echo "allowed_tools: \"${TASK_ALLOWED_TOOLS}\""
        fi
        if [[ -n "${TASK_ADD_DIRS:-}" ]]; then
            echo "add_dirs: \"${TASK_ADD_DIRS}\""
        fi
        echo "skip_if_exists: ${TASK_SKIP_IF_EXISTS:-true}"
        if [[ -n "${TASK_CLAUDE_BIN:-}" ]]; then
            echo "claude_bin: \"${TASK_CLAUDE_BIN}\""
        fi
    } > "$yaml"
}

task_remove() {
    local name="$1"
    local dir
    dir="$(task_dir "$name")"
    if [[ -d "$dir" ]]; then
        rm -rf "$dir"
    fi
    return 0
}
